name: XPLevels
main: XPLevels\Main
version: 1.0.0
api: 5.0.0
author: zyberpe

commands:
  xp:
    description: Manage raw XP
    usage: "/xp <add|remove|set|see> <player> <amount>"
    permission: xplevels.use

permissions:
  xplevels.use:
    default: op
